---
title: "新版TCGA数据下载_树下乘凉版"
output: html_document
editor_options: 
  chunk_output_type: console
---

```{r setup, include=FALSE}
knitr::opts_chunk$set(echo = TRUE,message = F,warning = F)
```

### 1.查看TCGA的33个project

```{r}
rm(list = ls())
library(TCGAbiolinks)
library(stringr)
library(SummarizedExperiment)
projs <- getGDCprojects()$project_id %>% 
  str_subset("TCGA")
projs
```


### 2.下载并整理表达矩阵

去这个链接，找到你要的癌症的count和临床信息数据，下载下来放在工作目录下

https://share.weiyun.com/ZMQdPBLC 密码：xjlshh

链接：https://pan.baidu.com/s/1HbIx-O_18zGCajUeHIHr0Q?pwd=xjls 
提取码：xjls 

```{r}
proj = "TCGA-STAD"
load("stad_exp.Rdata")
exp = stad
```

### 3.下载并整理临床信息

```{r}
load("stad_clinical.Rdata")
clinical = stad_clinical
```

### 4.表达矩阵行名ID转换

```{r}
library(tinyarray)
exp = trans_exp_new(exp)
exp[1:4,1:4]
```

gdc下载的数据从此处开始衔接

### 5.基因过滤

需要过滤一下那些在很多样本里表达量都为0或者表达量很低的基因。过滤标准不唯一。

过滤之前基因数量：

```{r}
nrow(exp)
```

#### 常用过滤标准1：

仅去除在所有样本里表达量都为零的基因

```{r}
exp1 = exp[rowSums(exp)>0,]
nrow(exp1)
```

#### 常用过滤标准2(推荐)：

仅保留在一半以上样本里表达的基因

```{r}
exp = exp[apply(exp, 1, function(x) sum(x > 0) > 0.5*ncol(exp)), ]
nrow(exp)
```


### 6.分组信息获取

根据样本ID的第14-15位，给样本分组（tumor和normal）

```{r}
Group = make_tcga_group(exp)
table(Group)
```

### 7.保存数据

```{r}
save(exp,Group,proj,clinical,file = paste0(proj,".Rdata"))
```
