---
title: "geo"
output: html_document
editor_options: 
  chunk_output_type: console
---

```{r setup, include=FALSE}
knitr::opts_chunk$set(
  collapse = TRUE,
  comment = "#>"
)
knitr::opts_chunk$set(fig.width = 10,fig.height = 7,collapse = TRUE)
knitr::opts_chunk$set(message = FALSE,warning = FALSE)
```

需要tinyarray包版本2.3.1及以上

```{r}
rm(list = ls())
#打破下载时间的限制,改前60秒，改后10w秒
options(timeout = 100000) 
options(scipen = 20)#不要以科学计数法表示

library(tinyarray)
packageVersion("tinyarray")
library(stringr)
geo = geo_download("GSE62254")
#看到数据范围0~5，明显不对劲
#从网页上面检查发现这个数据是log10，因此↓
exp = log2(10^geo$exp+1)

#exp = log2(exp+1)
boxplot(exp[,1:6],las = 2)
pd = geo$pd
gpl_number = geo$gpl

find_anno(geo$gpl)
library(hgu133plus2.db);ids <- toTable(hgu133plus2SYMBOL)
head(ids)
#将探针表达矩阵转换为基因表达矩阵
exp = trans_array(exp,ids)
exp[1:4,1:4]
```

### 临床信息整理

参考文献的附件
```{r}
a = rio::import("41591_2015_BFnm3850_MOESM34_ESM.xls")
#选列
clinical = a[,c("Tumor ID" ,
                "FU status0=alive without ds, 1=alive with recurren ds, 2=dead without ds, 3=dead d/t recurrent ds, 4=dead, unknown, 5= FU loss",
                "DFS\n(months)"  ,
                "OS\n(months)",
                "T","N","M",
                "sex",
                "pStage",
                "age")]
#规范event列格式，用0和1表示
colnames(clinical)[2]
table(clinical[,2],useNA = "always")
k1 = clinical[,2] %in% c(0,1) ;table(k1) #活着
k2 = clinical[,2]==0;table(k2)#无病
clinical$event = ifelse(k1,0,1)
clinical$dfsevent = ifelse(k2,0,1)
#第二列用完了，不要了
clinical=clinical[,-2]
#修改列名
colnames(clinical)[c(2,3,7,8)] = c("dfstime","time","gender","stage")
#有的T比较奇怪,转数字时这种转换不了的会直接变成NA
unique(clinical$`T`)
clinical$`T` = as.numeric(clinical$`T`)
```

临床信息合并

pd是从geo数据库里下载到的，clinical是文章附件里的，都有用

```{r}
head(pd)
```

可以看到，pd里面的patient:ch1列和clinical里面的Tumor ID是一样的，都是数字编号，可以用于连接

```{r}
table(pd$`patient:ch1` %in% clinical$`Tumor ID`)
pd = data.frame(number = rownames(pd),
                "Tumor ID" = pd$`patient:ch1`,check.names = F)
pd = merge(pd,clinical,by= "Tumor ID")
rownames(pd) = pd$number

head(pd)
#pd的行和exp的列顺序对应起来
s = intersect(rownames(pd),colnames(exp))
pd = pd[s,]
exp = exp[,s]
save(exp,pd,file = "geoexp.Rdata")
```
