---
title: "lasso"
output: html_document
editor_options: 
  chunk_output_type: console
---

```{r setup, include=FALSE}
knitr::opts_chunk$set(echo = TRUE,message = F,warning = F)
```

### 模型

```{r}
rm(list = ls())
load("../3_GEO_dat_pre/geoexp.Rdata")
load("../4_tcga_model/TCGA-STADcox_fp.Rdata")
load("../4_tcga_model/TCGA-STAD_sur_model.Rdata")
library(survival)
library(survminer)
```

计算GEO数据的风险评分

```{r}
fp = apply(exp[names(model$coefficients),], 2, function(x){
  sum(x * model$coefficients)
});head(fp)
pd$Riskscore = fp
pd$Risk = ifelse(pd$Riskscore<median(pd$Riskscore),"low","high")
pd$Risk = factor(pd$Risk,levels = c("low","high"))
```

#### OS KM-plot

```{r}
sfit <- survfit(Surv(time, event)~Risk, data=pd)
ggsurvplot(sfit,palette = c("#E7B800", "#2E9FDF"),
           pval =TRUE,
           conf.int =TRUE,xlab ="Time in months", 
           ggtheme =theme_light())
```

### DFS KM-plot
```{r}
sfit <- survfit(Surv(dfstime, dfsevent)~Risk, data=pd)
ggsurvplot(sfit,palette = c("#E7B800", "#2E9FDF"),
           pval =TRUE,
           conf.int =TRUE,xlab ="Time in months", 
           ggtheme =theme_light())
```

### OS-timeROC

```{r}
library(survminer)
library(survival)
library(timeROC)
result <-with(pd, timeROC(T=time,
                     delta=event,
                     marker=Riskscore,
                     cause=1,
                     times=c(12,36,60),
                     iid = TRUE))
plot_dat = data.frame(fpr = as.numeric(result$FP),
                 tpr = as.numeric(result$TP),
                 time = rep(as.factor(c(12,36,60)),each = nrow(result$TP)))

library(ggplot2)
ggplot() + 
  geom_line(data = plot_dat,aes(x = fpr, y = tpr,color = time),linewidth = 1) + 
  scale_color_manual(name = NULL,values = c("#2874C5", "#f87669", "#e6b707"),
                     labels = paste0("AUC of ",c(1,3,5),"-y survival: ",
                                     format(round(result$AUC,2),nsmall = 2)))+
  geom_line(aes(x=c(0,1),y=c(0,1)),color = "grey")+
  theme_bw()+
  theme(panel.grid = element_blank(),
        legend.background = element_rect(linetype = 1, linewidth = 0.2, colour = "black"),
        legend.position = c(0.765,0.125))+
  scale_x_continuous(expand = c(0.005,0.005))+
  scale_y_continuous(expand = c(0.005,0.005))+
  labs(x = "1 - Specificity",
       y = "Sensitivity")+
  coord_fixed()
```

### DFS-timeROC

```{r}
library(survminer)
library(survival)
library(timeROC)
result <-with(pd, timeROC(T=dfstime,
                     delta=dfsevent,
                     marker=Riskscore,
                     cause=1,
                     times=c(12,36,60),
                     iid = TRUE))
plot_dat = data.frame(fpr = as.numeric(result$FP),
                 tpr = as.numeric(result$TP),
                 time = rep(as.factor(c(12,36,60)),each = nrow(result$TP)))

library(ggplot2)
ggplot() + 
  geom_line(data = plot_dat,aes(x = fpr, y = tpr,color = time),linewidth = 1) + 
  scale_color_manual(name = NULL,values = c("#2874C5", "#f87669", "#e6b707"),
                     labels = paste0("AUC of ",c(1,3,5),"-y survival: ",
                                     format(round(result$AUC,2),nsmall = 2)))+
  geom_line(aes(x=c(0,1),y=c(0,1)),color = "grey")+
  theme_bw()+
  theme(panel.grid = element_blank(),
        legend.background = element_rect(linetype = 1, linewidth = 0.2, colour = "black"),
        legend.position = c(0.765,0.125))+
  scale_x_continuous(expand = c(0.005,0.005))+
  scale_y_continuous(expand = c(0.005,0.005))+
  labs(x = "1 - Specificity",
       y = "Sensitivity")+
  coord_fixed()
```

