---
title: "3.enrich"
output: html_document
editor_options: 
  chunk_output_type: console
---

```{r setup, include=FALSE}
knitr::opts_chunk$set(
  collapse = TRUE,
  comment = "#>"
)
knitr::opts_chunk$set(fig.width = 8,fig.height = 6,collapse = TRUE)
knitr::opts_chunk$set(message = FALSE,warning = FALSE)
```

### 1.GSEA

只能拿一个包的差异分析结果来做

```{r}
rm(list = ls())
library(GSEABase) 
library(clusterProfiler)
library(org.Hs.eg.db)
library(ggplot2)
library(stringr)
library(enrichplot)
library(msigdbr)
load("risk_DEG.Rdata")
deg = DEG1
library(clusterProfiler)
output <- bitr(rownames(deg),
               fromType = 'SYMBOL',
               toType = 'ENTREZID',
               OrgDb = 'org.Hs.eg.db')
deg = merge(deg,output,by.x = "row.names",by.y = "SYMBOL")

ge = deg$log2FoldChange # 注意换不同的R包时logFC列的列名不同
names(ge) = deg$Row.names
ge = sort(ge,decreasing = T)
head(ge)

geneset <- msigdbr(species = "Homo sapiens",category = "H") %>%
  dplyr::select(gs_name,gene_symbol)
geneset[1:4,]
geneset$gs_name = geneset$gs_name %>%
  str_split("_",simplify = T,n = 2)%>%
  .[,2]%>%
  str_replace_all("_"," ") %>% 
  str_to_sentence()
em <- GSEA(ge, TERM2GENE = geneset)
#画个图来看看
gseaplot2(em, geneSetID = 1, title = em$Description[1])
gseaplot2(em, geneSetID = 1:3,pvalue_table = T)
#气泡图，展示geneset被激活还是抑制
dotplot(em,split=".sign")+facet_grid(~.sign)
ridgeplot(em)
```

### 2.ORA

三个R包差异基因交集，或者一个R包的差异基因。

```{r}
rm(list = ls())  
library(clusterProfiler)
library(ggthemes)
library(org.Hs.eg.db)
library(dplyr)
library(ggplot2)
library(stringr)
library(enrichplot)

#(1)输入数据
load("risk_DEG.Rdata")
library(tinyarray)
deg = DEG1
g = rownames(deg)[deg$change!="NOT"]
output <- bitr(g,
             fromType = 'SYMBOL',
             toType = 'ENTREZID',
             OrgDb = 'org.Hs.eg.db')
gene_diff = output$ENTREZID

#(2)富集
ekk <- enrichKEGG(gene = gene_diff,
                  organism = 'hsa')
ekk <- setReadable(ekk,
                   OrgDb = org.Hs.eg.db,
                   keyType = "ENTREZID")
ego <- enrichGO(gene = gene_diff,
                OrgDb= org.Hs.eg.db,
                ont = "ALL",
                readable = TRUE)
#setReadable和readable = TRUE都是把富集结果表格里的基因名称转为symbol
class(ekk)

#(3)可视化
barplot(ego, split = "ONTOLOGY") + 
  facet_grid(ONTOLOGY ~ ., space = "free_y",scales = "free_y") 
barplot(ekk)
#或者是dotplot
```

#### GO圈圈图

```{r}
library(GOplot)
ego <- data.frame(ego) 
colnames(ego)
ego <- ego %>% group_by(ONTOLOGY) %>% slice(1:4) %>%
  select(ONTOLOGY,ID,Description,geneID,p.adjust)

ego$geneID <- str_replace_all(ego$geneID,"/",",") 
names(ego)=c("Category","ID","Term","Genes","adj_pval")
head(ego)

genes = data.frame(ID=rownames(deg),
                   logFC=deg$log2FoldChange)
head(genes)
circ <- circle_dat(ego,genes)
GOCircle(circ)
```

### KEGG 弦图

```{r}
ekk <- data.frame(ekk) 
colnames(ekk)
ekk <- ekk %>%  slice(1:4) %>%
  select(category,ID,Description,geneID,p.adjust)

ekk$geneID <- str_replace_all(ekk$geneID,"/",",") 
names(ekk)=c("Category","ID","Term","Genes","adj_pval")
head(ekk)

genes = data.frame(ID=rownames(deg),
                   logFC=deg$log2FoldChange)
head(genes)
circ <- circle_dat(ekk,genes)
chord <- chord_dat(data=circ, genes=genes,process = ekk$Term) # 

GOChord(chord, space = 0.02, gene.order = 'logFC', gene.space = 0.25, gene.size = 3)
```

