

```{r setup, include=FALSE}
knitr::opts_chunk$set(
  collapse = TRUE,
  comment = "#>"
)
knitr::opts_chunk$set(fig.width = 6,fig.height = 6,collapse = TRUE)
knitr::opts_chunk$set(message = FALSE)
```

### 1.起个项目名字

TCGA的数据，统一叫TCGA-xxxx，非TCGA的数据随意起名，不要有特殊字符即可。

```{r}
proj = "TCGA-CHOL"
```

### 2.读取和整理数据

### 2.1 表达矩阵

```{r}
dat = read.table("TCGA-CHOL.htseq_counts.tsv.gz",check.names = F,row.names = 1,header = T)
range(dat)
#逆转log,发现需要逆转，才逆转
dat = as.matrix(2^dat - 1)
dat[1:4,1:4]
# 深坑一个
dat[97,9]
as.character(dat[97,9]) #眼见不一定为实吧。

# 转换为整数矩阵
exp = round(dat)
# 检查
as.character(exp[97,9])
```

#### 2.2 临床信息

```{r}
clinical = read.delim("TCGA-CHOL.GDC_phenotype.tsv.gz")
clinical[1:4,1:4]
```

### 3.表达矩阵行名ID转换

```{r}
library(tinyarray)
exp = trans_exp_new(exp)
exp[1:4,1:4]
```

### 4.基因过滤

需要过滤一下那些在很多样本里表达量都为0或者表达量很低的基因。过滤标准不唯一。

过滤之前基因数量：

```{r}
nrow(exp)
```

#### 常用过滤标准1：

仅去除在所有样本里表达量都为零的基因

```{r}
exp1 = exp[rowSums(exp)>0,]
nrow(exp1)
```

#### 常用过滤标准2(推荐)：

仅保留在一半以上样本里表达的基因

```{r}
exp = exp[apply(exp, 1, function(x) sum(x > 0) > 0.5*ncol(exp)), ]
nrow(exp)
```

### 5.分组信息获取

TCGA的数据，直接用make_tcga_group给样本分组（tumor和normal），其他地方的数据分组方式参考芯片数据pipeline/02_group_ids.R

```{r}
library(tinyarray)
Group = make_tcga_group(exp)
table(Group)
```

### 6.保存数据

```{r}
save(exp,Group,proj,clinical,file = paste0(proj,".Rdata"))
```

