---
title: "物种分布与模拟_多物种多模型分析"
author: "何昆"
date: "2024-05-31"
output:
  word_document: default
  pdf_document: default
---

## R Markdown

```{r}
#加载R包
library(SSDM)
library(raster)
```

```{r}

#### 示例数据（只有示例数据跑通，才能验证该模型在本电脑可用）

#SSDM的示例
# 加载环境变量
Env <- load_var(system.file('extdata', package = 'SSDM'), categorical = 'SUBSTRATE', verbose = FALSE)

# 打印环境变量
Env

# 加载物种出现数据
Occ <- load_occ(path = system.file('extdata', package = 'SSDM'), Env, Xcol = 'LONGITUDE', Ycol = 'LATITUDE',
                file = 'Occurrences.csv', sep = ',', verbose = FALSE)

# 查看物种出现数据的前几行
head(Occ)

#单个物种单个模型
#结果：
#（1）一个连续的栅格地图，显示仅存在数据的栖息地适宜性，以及对于存在/缺失数据的存在概率；
#（2）一个基于栖息地适宜性阈值的二元存在/缺失栅格地图
# 使用广义线性模型进行物种分布建模
SDM <- modelling('GLM', subset(Occurrences, Occurrences$SPECIES == 'elliptica'),Env, Xcol = 'LONGITUDE', Ycol = 'LATITUDE', verbose = FALSE, save = T)
# 绘制物种分布模型的预测图
#这一段可以看视频讲解，以理解
SDM@evaluation
SDM@variable.importance
SDM@data
SDM@parameters
#SDM@ 可以加很多变量，可以自己在输入@之后在弹出的变量中选

plot(SDM@projection, main = 'SDM for Cryptocarya elliptica with GLM algorithm')#物种分布图
plot (SDM@binary)

```

```{r}
#### 多模型 & 单一物种示例数据（只有示例数据跑通，才能验证该模型在本电脑可用）
#rep = 1是指重复次数为1，但实际使用时一般会设置为rep = 10
# 多模型 & 单一物种 - Cryptocarya elliptica
#目的：降低不同算法之间的局限性
#方法：（1）对SDM输出的简单平均：（2）基于用户指定的度量标准或一组度量标准的加权平均
#结果：
#（1）基于集合模型的物种分布图
#（2）不确定性图
#（3）不同算法之间的相关性分析

ESDM <- ensemble_modelling(c('CTA', 'MARS'), subset(Occurrences, Occurrences$SPECIES == 'elliptica'),
                           Env, rep = 1, Xcol = 'LONGITUDE', Ycol = 'LATITUDE', 
                           ensemble.thresh = 0, verbose = FALSE, save = T)
# 使用ESDM对象的projection数据绘制分布图，标题为'ESDM for Cryptocarya elliptica with CTA and MARS algorithms'
plot(ESDM@projection, main = 'ESDM\nfor Cryptocarya elliptica\nwith CTA and MARS algorithms')

# 打印ESDM模型中算法的相关性评估结果
ESDM@algorithm.correlation

# 可以使用write.csv(ESDM@algorithm.correlation)保存

# 打印ESDM模型中算法的评估结果
ESDM@algorithm.evaluation

# 打印ESDM模型中变量的重要性评估结果
ESDM@variable.importance

# 绘制ESDM模型的不确定性图，这种图通常用于科学文章中展示模型预测的不确定性
plot(ESDM@uncertainty) # 不确定性图可用于文章

# 绘制ESDM模型的二值分布图，通常用于展示物种存在的概率
plot(ESDM@binary)

```

```{r}
#### 多模型 & 多物种示例数据（只有示例数据跑通，才能验证该模型在本电脑可用）

SSDM <- stack_modelling(c('CTA', 'SVM'), Occurrences, Env, rep = 1, ensemble.thresh = 0,
                       Xcol = 'LONGITUDE', Ycol = 'LATITUDE',
                       Spcol = 'SPECIES', method = "pSSDM", verbose = FALSE, save = T)
plot(SSDM@diversity.map, main = 'SSDM\nfor Cryptocarya genus\nwith CTA and SVM algorithms')

#也可以运行下面的代码单独保存
#writeRaster(SSDM@diversity.map, "diversity.tif")
```

```{r}
#单个物种单个模型分析
#加载R包
library(SSDM)
library(raster)
library(geodata)#这个包有些函数和SSDM冲突，使用完之后重新加载一下ssdm
library(rJava)
library(terra)
library(sp)
```

```{r}
#导入数据
#occ_final_mul.csv应该不是occ_final_.csv。经过研究，occ_final_mul.csv应该是有多个物种数据储存在一个文件夹，以方便多物种多模型演示，而不是前面的演示数据occ_final_.csv的单物种，这里先使用occ_final_.csv，等到多物种模型时改为occ_final_mul.csv
bioclim <- worldclim_global('worldclim', var = "bio", res = 5)
bioclim
clim <- raster::stack(bioclim)
clim
Env <- clim
Occ <- load_occ(path = getwd(), Env, Xcol = 'Long', Ycol = 'Lat', file = 'occ_final.csv', sep = ',', verbose = FALSE)
head(Occ)
```

```{r}
library(SSDM)
# （1）单一模型 & 单一物种
SDM <- modelling('GLM', subset(Occ, Occ$Species == 'Cunninghamia lanceolata'),
                 Env, Xcol = 'Long', Ycol = 'Lat', select = TRUE, 
                 select.metric = c("AUC"), 
                 select.thresh = c(0.75), verbose = FALSE, GUI = FALSE, save = T)
plot(SDM@projection, main = 'SDM\nwith GLM algorithm')
plot(SDM@binary)
```

```{r}

# （2）多模型 & 单一物种
#可选模型GAM,GLM,MARS,MAXENT,CTA,GBM,ANN,RF,SVM,但有时更改模型可能意味着需要不同的基础包，比如MAXENT的rjava，不是简单的换一下名字就可以
#rep = 1是指重复次数为1，但实际使用时一般会设置为rep = 10
#结果文件中VarImp.csv可以查看变量的贡献值，Data.csv可以用来相关性筛选变量
ESDM <- ensemble_modelling(c('CTA', 'MARS'), subset(Occ, Occ$Species == 'Cunninghamia lanceolata'),
                           Env, rep = 1, Xcol = 'Long', Ycol = 'Lat', 
                           ensemble.thresh = 0.75, verbose = FALSE, save = T)
plot(ESDM@projection, main = 'ESDM\nwith CTA and MARS algorithms')
```

```{r}
#导入数据
#在接下来因为需要多物种，为减轻计算压力，自己重新倒入自己修改过的occ_final_mul.csv，其中包含100个数据，A，B两个物种
bioclim <- worldclim_global('worldclim', var = "bio", res = 5)
bioclim
clim <- raster::stack(bioclim)
clim
Env <- clim
Occ <- load_occ(path = getwd(), Env, Xcol = 'Long', Ycol = 'Lat', file = 'occ_final_mul.csv', sep = ',', verbose = FALSE)
head(Occ)
```

```{r}
# （2）多模型 & 多物种
#可选模型GAM,GLM,MARS,MAXENT,CTA,GBM,ANN,RF,SVM,但有时更改模型可能意味着需要不同的基础包，比如MAXENT的rjava，不是简单的换一下名字就可以
#rep = 1是指重复次数为1，但实际使用时一般会设置为rep = 10
#结果文件中VarImp.csv可以查看变量的贡献值，Data.csv可以用来相关性筛选变量
SSDM <- stack_modelling(c('CTA', 'SVM'), Occurrences = Occ, Env, rep = 1, ensemble.thresh = 0.75,
                       Xcol = 'Long', Ycol = 'Lat', save = T,
                       Spcol = 'Species', method = "pSSDM", verbose = FALSE)
plot(SSDM@diversity.map, main = 'SSDM with CTA and SVM algorithms')
SSDM@evaluation
SSDM@uncertainty
```

```{r}
# 预测未来的生物地理环境模型
bioclim_fu <- cmip6_world("CNRM-CM6-1", ssp="585", time="2061-2080", var="bioc", res=5, path=getwd())
# 创建环境新矩阵
Env_new <- stack(bioclim_fu)
# 设置矩阵的坐标参考系，这里坐标系一样，所以不用运行
#crs(Env_new) <- Env
# 重命名矩阵的列名
names(Env_new) <- names(Env)
Env_new



```

```{r}
# 预测未来的生物地理环境模型
#bioclim_fu1 <- cmip6_world("CNRM-CM6-1", ssp="585", time="2061-2080", var="bioc", res=5, path=getwd())
# 创建环境新矩阵
#Env_new1 <- stack(bioclim_fu)
# 设置矩阵的坐标参考系，这里坐标系一样，所以不用运行
#crs(Env_new1) <- Env
# 重命名矩阵的列名
#names(Env_new1) <- names(Env)
#Env_new1



```

```{r}
#使用循环提取拆分当前环境变量，共19层
# 实操：分别获取当前和未来的环境数据，并统一坐标系和名称。

# 获取栅格堆栈中的栅格数量
##（2）
num_rasters <- nlayers(Env)  
# 使用nlayers函数获取Env栅格堆栈中的层数
for (i in 1:num_rasters) {  
  # 遍历每个栅格层
  current_raster <- Env[[i]]  
  # 创建文件夹
  if(!file.exists("D:\\R\\Rdata\\curent")) dir.create("D:\\R\\Rdata\\curent")
  # 获取当前的栅格层
  filename <- paste0("D:\\R\\Rdata\\curent\\","bio_", i, ".tif")  
  # 创建文件名，格式为bio_1.tif, bio_2.tif等
  writeRaster(current_raster, filename, format = "GTiff", overwrite=TRUE)  
  # 将栅格数据写入GeoTIFF格式的文件
  cat("Saved", filename, "\n")  
  # 在控制台输出保存文件的信息
}

```

```{r}

# 实操：分别获取当前和未来的环境数据并进行SDM模型的预测，并统一坐标系和名称。
#使用循环提取拆分当前环境变量，共19层
# 获取栅格堆栈中的栅格数量
##（2）
num_rasters <- nlayers(Env_new)  
# 使用nlayers函数获取Env栅格堆栈中的层数
for (i in 1:num_rasters) {  
  # 遍历每个栅格层
  current_raster <- Env_new[[i]]  
  # 创建文件夹
  if(!file.exists("D:\\R\\Rdata\\future")) dir.create("D:\\R\\Rdata\\future")
  # 获取当前的栅格层
  filename <- paste0("D:\\R\\Rdata\\future\\","bio_", i, ".tif")  
  # 创建文件名，格式为bio_1.tif, bio_2.tif等
  writeRaster(current_raster, filename, format = "GTiff", overwrite=TRUE)  
  # 将栅格数据写入GeoTIFF格式的文件
  cat("Saved", filename, "\n")  
  # 在控制台输出保存文件的信息
}

```

```{r}
#单物种单算法模型预测模拟
SDM_projection <- SSDM::project(SDM, Env_new)
# 绘制结果
plot(SDM_projection@projection)
# 将结果写入文件
writeRaster(SDM_projection@projection, "D:\\R\\Rdata\\future.tif", format="GTiff", overwrite=TRUE)

#查看结果对比
distribution<-raster::stack (SDM@projection, SDM_projection@projection) 
plot(distribution) 
#因为SDM@projection和SDM_projection@projection的标尺是一样的，所以可以使用下列函数，共用标尺
library(rasterVis)
levelplot(distribution)

levelplot(distribution, margin = list(FUN = ' median '), par.settings=RdBuTheme)
```

```{r}
# 实操：基于ESDM模型进行物种分布的模拟与预测，并可视化物种潜在分布图与预测分布图

# 使用project函数将ESDM模型投影到新的环境数据上
ESDM_projection <- SSDM::project(ESDM, Env_new, save=T) 

# 将当前和未来的投影以及不确定性数据堆叠到一个栅格堆栈中
re_ESDM <- raster::stack(ESDM@projection, ESDM_projection@projection, ESDM@uncertainty, ESDM_projection@uncertainty)

# 为栅格堆栈中的每个层命名，以区分当前和未来的投影及不确定性
names(re_ESDM) <- c("current-projection", "future-projection", "current-uncertainty", "future-uncertainty")

# 绘制栅格堆栈，可视化物种的潜在分布和预测分布
plot(re_ESDM)
  
```

```{r}
# 实操：图形化界面操作
# 安装shinyFiles包，因为SSDM::gui()依赖
# install.packages("shinyFiles")
#看第四节课结尾和第五节课开始
SSDM::gui()
```

```{r}
#上面就是所有的物种模拟与预测，下面是生态位动态量化，可能不用，所以没提取，用时再提去
```

```{r}
#### 物种气候生态位动态量化
```

```{r}
install.packages("ecospat")
library("ecospat")
```


```{r}
# 加载所需的库
library(ecospat)  # 加载ecospat库，用于物种分布建模
library(maps)     # 加载maps库，用于绘制地图
library(rgeos)    # 加载rgeos库，提供接口以访问GEOS库进行地理空间操作
library(ade4)     # 加载ade4库，用于多元数据分析和环境数据探索
library(SSDM)     # 加载SSDM库，用于物种分布建模
library(raster)   # 加载raster库，用于栅格数据操作
library(ape)      # 加载ape库，用于分子系统发育和进化分析
library(sp)       # 加载sp库，用于空间数据的处理和分析
library(geodata)  # 加载geodata库，用于获取地理和气候数据
```


```{r}
# 读取数据
# （1）分布数据
occl <- read.csv("E:/maxenttry/data/occl.csv")  # 读取第一个分布数据文件
occ2 <- read.csv("E:/maxenttry/data/occ2.csv")  # 读取第二个分布数据文件

# 环境数据
## 方法一：
clim_list <- list.files("E:/maxenttry/data/bioclim/", pattern=".bil", full.names = TRUE)  # 获取bioclim文件夹中所有.bil文件的路径
bioclim <- raster::stack(clim_list)  # 将这些.bil文件堆叠成一个栅格堆栈
bioclim # 打印栅格堆栈的信息

## 方法二：
bioclim <- worldclim_global('worldclim', var="bio", res=0.5)  # 从worldclim获取全球生物气候数据



env1_clim <- raster::extract(bioclim, occl[, -1])  # 从bioclim栅格中提取第一个分布数据的环境变量
env2_clim <- raster::extract(bioclim, occ2[, -1])  # 从bioclim栅格中提取第二个分布数据的环境变量

# 更新列名以移除前缀,可以不用
#colnames(env1_clim) <- gsub("wc2.1_30s_", "", colnames(env1_clim))
#colnames(env2_clim) <- gsub("wc2.1_30s_", "", colnames(env2_clim))

# 将分布数据和环境变量合并
env11 <- cbind(occl, env1_clim[, c(2:20)])
env22 <- cbind(occ2, env2_clim[, c(2:20)])

# 移除含有缺失值的行
env11 <- na.omit(env11)
env22 <- na.omit(env22)

# 打印合并后数据的头部信息
head(env11)

# 输出数据
write.csv(env11, "E:/maxenttry/data/occ1_climate.csv")  # 将env1数据写入CSV文件
write.csv(env22, "E:/maxenttry/data/occ2_climate.csv")  # 将env2数据写入CSV文件

```
